openapi: "3.0.3"
info:
  title: "Books REST API"
  description: "Программный интерфейс ядра Books"
  version: "23.1"
servers:
- url: "/"
paths:
  /html-thymeleaf:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ThymeleafContent"
  /about:
    get:
      description: "Возвращает информацию о приложении."
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
  /catalog:
    get:
      description: "Книжный каталог."
      responses:
        "200":
          description: "OK"
          content:
            application/xml:
              schema:
                type: "string"
  /catalog/authors:
    get:
      description: "По авторам."
      responses:
        "200":
          description: "OK"
          content:
            application/xml:
              schema:
                type: "string"
  /catalog/authors/{id}/books:
    get:
      description: "Все книги автора."
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            application/xml:
              schema:
                type: "string"
  /catalog/authors/{id}/sequences:
    get:
      description: "По сериям."
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            application/xml:
              schema:
                type: "string"
  /catalog/authors/{id}/sequences/{sequenceId}/books:
    get:
      description: "Все книги серии."
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "sequenceId"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            application/xml:
              schema:
                type: "string"
  /catalog/genres:
    get:
      description: "По жанрам."
      responses:
        "200":
          description: "OK"
          content:
            application/xml:
              schema:
                type: "string"
  /catalog/genres/{id}/books:
    get:
      description: "Все книги жанра."
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            application/xml:
              schema:
                type: "string"
  /catalog/recent:
    get:
      description: "Недавно добавленные книги."
      responses:
        "200":
          description: "OK"
          content:
            application/xml:
              schema:
                type: "string"
  /catalog/recommended:
    get:
      description: "Рекомендуемые книги."
      responses:
        "200":
          description: "OK"
          content:
            application/xml:
              schema:
                type: "string"
  /catalog/unread:
    get:
      description: "Непрочитанные книги."
      responses:
        "200":
          description: "OK"
          content:
            application/xml:
              schema:
                type: "string"
  /catalog/unverified:
    get:
      description: "Непроверенные книги."
      responses:
        "200":
          description: "OK"
          content:
            application/xml:
              schema:
                type: "string"
components:
  schemas:
    Map:
      type: "object"
      properties: {}
    HeaderValueParam:
      type: "object"
      properties:
        name:
          type: "string"
        value:
          type: "string"
        escapeValue:
          type: "boolean"
    ContentType:
      type: "object"
      properties:
        contentType:
          type: "string"
        contentSubtype:
          type: "string"
        parameters:
          type: "array"
          items:
            $ref: "#/components/schemas/HeaderValueParam"
    Locale:
      type: "object"
      properties: {}
    ThymeleafContent:
      type: "object"
      properties:
        template:
          type: "string"
        model:
          $ref: "#/components/schemas/Map"
        etag:
          type: "string"
        contentType:
          $ref: "#/components/schemas/ContentType"
        locale:
          $ref: "#/components/schemas/Locale"
        fragments:
          type: "array"
          items:
            type: "string"