spring:
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:file:~/.local/share/books/db;AUTO_SERVER=TRUE
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

books:
  fileMonitor:
    source: /home/dmitry/Загрузки
    processed: /home/dmitry/Загрузки/processed
    forceCompress: true
