spring:
  datasource:
    url: jdbc:postgresql://localhost:5712/books
    password: postgres
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
#      ddl-auto: create
      ddl-auto: update


books:
  import:
    forceFb2CompressForStore: true
  fileMonitor:
    source: /home/dmitry/Загрузки/books/autoimport
    processed: /home/dmitry/Загрузки/books/processed
