spring:
  datasource:
    url: jdbc:postgresql://localhost:5711/books
    password: postgres
    username: postgres
  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: update


books:
  import:
    forceFb2CompressForStore: true
  fileMonitor:
    source: /home/dmitry/Загрузки
    processed: /home/dmitry/Загрузки/books/processed
