spring:
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:file:/var/local/projects/books-db
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

books:
  root: /home/dmitry/yandex.disk/Книги
  importer:
    source: /home/dmitry/Загрузки
    target: /home/dmitry/Загрузки/books
    processed: /home/dmitry/Загрузки/processed
